# Include this route enhancer config:
# imports:
#  - { resource: "EXT:t3extblog/Configuration/Routes/Default.yaml" }

imports:
  - { resource: "EXT:t3extblog/Configuration/Routes/Blogsystem.yaml" }
  - { resource: "EXT:t3extblog/Configuration/Routes/SubscriptionManager.yaml" }
  - { resource: "EXT:t3extblog/Configuration/Routes/BlogSubscription.yaml" }
